---
language: python
python: "2.7"
sudo: required
dist: trusty

# environment variables
env:
  - ANSIBLE_INVENTORY=hosts

# update apt indices, install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-dev python-pip gcc git

# install ansible from pip
install:
  - pip install --upgrade pip
  - pip install --upgrade ansible

# run tests
script:
  # run syntax checks
  - "ansible-playbook tests/test.yml -i tests/hosts --connection=local --syntax-check"

  # run score tasks
  # NOTE: Ignore Section 13.20, 8.3.1 & 4.5 due to timeouts on Travis-CI build env.
  - "ansible-playbook tests/test.yml -i tests/hosts --connection=local --tags=scored --skip-tags=section4.5,section13.20,section8.3.1"

# vim: set sw=2 ts=2:
