---
#file: tasks/section-08-level-2.yml

- name: 8.1.1 Configure Data Retention
  debug: msg="*** When auditing, it is important to carefully configure the storage requirements for audit logs"
  tags:
    - section8.1.1

- name: 8.1.1.1 Configure Audit Log Storage Size (Not Scored)
  lineinfile: dest="/etc/audit/auditd.conf" regex="^max_log_file" line="max_log_file = 10"
  tags:
    - notscored
    - section8.1.1
    - section8.1.1.1

- name: 8.1.1.2 Disable System on Audit Log Full (Not Scored)
  lineinfile: dest="/etc/audit/auditd.conf" regex={{ item.regex }} line={{ item.line }}
  with_items:
    - { regex: "^space_left_action", line: "space_left_action = email" }
    - { regex: "^action_mail_acct", line: "action_mail_acct = root" }
    - { regex: "^admin_space_left_action", line: "admin_space_left_action = halt" }
  tags:
    - notscored
    - section8.1.1
    - section8.1.1.2

- name: 8.1.1.3 Keep All Auditing Information (Scored)
  lineinfile: dest="/etc/audit/auditd.conf" regex="^max_log_file_action" line="max_log_file_action = keep_logs"
  tags:
    - scored
    - section8.1.1
    - section8.1.1.3

- name: 8.1.2 Install and Enable auditd Service (Scored)
  apt: name=auditd update_cache=yes state=installed
  tags:
    - scored
    - section8.1.2

- name: 8.1.2 Install and Enable auditd Service (Scored)
  service: name=auditd state=started enabled=yes
  tags:
    - scored
    - section8.1.2
# vim: set sw=2 ts=2:
