---
# file: tasks/section-01.yml

- name: 1.1 Install Updates, Patches and Additional Security Software (Not Scored)
  apt: upgrade=dist update_cache=yes
  tags:
    - notscored
    - section1.1

# vim: set sw=2 ts=2:
