---
#file: tasks/section-12-level-1.yml

- name: 12.1 & 12.4 Verify Permissions on /etc/passwd (Scored)
  file: path=/etc/passwd owner=root group=root mode=0644
  tags:
    - scored
    - section12.1
    - section12.4

- name: 12.2  & 12.5 Verify Permissions on /etc/shadow (Scored)
  file: path=/etc/shadow owner=root group=root mode=0600
  tags:
    - scored
    - section12.2

# vim: set sw=2 ts=2:
