---
# file: tasks/section-13-level-1.yml

- name: 13.1 Ensure Password Fields are Not Empty (Scored)
#  shell: /bin/cat /etc/shadow | /usr/bin/awk -F: '($2 == "" ) { print $1 " does not have a password "}'
  debug: msg="*** Evaluate your infrastructure before locking passwordless accounts"
  tags:
    - scored
    - section13.1

- name: 13.2 Verify No Legacy "+" Entries Exist in /etc/passwd File (Scored)
#  shell: /bin/grep '^+:' /etc/passwd
  debug: msg="*** Delete entries in /etc/password provided by `grep '^+:' /etc/passwd`"
  tags:
    - scored
    - section13.2

- name: 13.3 Verify No Legacy "+" Entries Exist in /etc/shadow File (Scored)
#  shell: /bin/grep '^+:' /etc/shadow
  debug: msg="*** Delete entries in /etc/shadow provided by `grep '^+:' /etc/shadow`"
  tags:
    - scored
    - section13.3

- name: 13.4 Verify No Legacy "+" Entries Exist in /etc/group File (Scored)
#  shell: /bin/grep '^+:' /etc/group
  debug: msg="*** Delete entries in /etc/group provided by `grep '^+:' /etc/group`"
  tags:
    - scored
    - section13.4

- name: 13.5 Verify No UID 0 Accounts Exist Other Than root (Scored)
#  shell:/bin/cat /etc/passwd | /usr/bin/awk -F: '($3 == 0) { print $1 }'
  debug: msg="*** Ensure that only the word 'root' is returned by `cat /etc/passwd | /usr/bin/awk -F: '($3 == 0) { print $1 }`"
  tags:
    - scored
    - section13.5

# vim: set sw=2 ts=2:
