---
#file: tasks/section-08-level-2.yml

- name: 8.1.1 Configure Data Retention
  debug: msg="*** When auditing, it is important to carefully configure the storage requirements for audit logs"
  tags:
    - section8.1.1

- name: 8.1.1.1 Configure Audit Log Storage Size (Not Scored)
  lineinfile: dest="/etc/audit/auditd.conf" regex="^max_log_file" line="max_log_file = 10"
  notify: restart auditd
  tags:
    - notscored
    - section8.1.1
    - section8.1.1.1

- name: 8.1.1.2 Disable System on Audit Log Full (Not Scored)
  lineinfile: dest="/etc/audit/auditd.conf" regex={{ item.regex }} line={{ item.line }}
  with_items:
    - { regex: "^space_left_action", line: "space_left_action = email" }
    - { regex: "^action_mail_acct", line: "action_mail_acct = root" }
    - { regex: "^admin_space_left_action", line: "admin_space_left_action = halt" }
  notify: restart auditd
  tags:
    - notscored
    - section8.1.1
    - section8.1.1.2

- name: 8.1.1.3 Keep All Auditing Information (Scored)
  lineinfile: dest="/etc/audit/auditd.conf" regex="^max_log_file_action" line="max_log_file_action = keep_logs" state=present
  notify: restart auditd
  tags:
    - scored
    - section8.1.1
    - section8.1.1.3

- name: 8.1.2 Install and Enable auditd Service (Scored)
  apt: name=auditd update_cache=yes state=installed
  tags:
    - scored
    - section8.1.2

- name: 8.1.2 Install and Enable auditd Service (Scored)
  service: name=auditd state=started enabled=yes
  tags:
    - scored
    - section8.1.2

#TODO: find a way to append at the end of a line
- name: 8.1.3 Enable Auditing for Processes That Start Prior to auditd (Scored)
  lineinfile: dest=/boot/grub/grub.cfg backup=True backrefs=True regexp='(^GRUB_CMDLINE_LINUX(\s+(?!audit=1)[\w=/\-\.]+)*)\s*$' line='\1 audit=1' state=present
  notify: update grub
  tags:
    - scored
    - section8.1.3

- name: 8.1.4 Record Events That Modify Date and Time Information (Scored)
  lineinfile: dest=/etc/audit/audit.rules line={{ item }} insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change"
    - "-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change"
    - "-a always,exit -F arch=b64 -S clock_settime -k time-change"
    - "-a always,exit -F arch=b32 -S clock_settime -k time-change"
    - "-w /etc/localtime -p wa -k time-change"
  when: ansible_machine == "x86_64"
  notify: restart auditd
  tags:
    - scored
    - section8.1.4

- name: 8.1.4 Record Events That Modify Date and Time Information (Scored)
  lineinfile: dest=/etc/audit/audit.rules line={{ item }} insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change"
    - "-a always,exit -F arch=b32 -S clock_settime -k time-change"
    - "-w /etc/localtime -p wa -k time-change"
  when: ansible_machine == "i686"
  notify: restart auditd
  tags:
    - scored
    - section8.1.4

- name: 8.1.5 Record Events That Modify User/Group Information (Scored)
  lineinfile: dest=/etc/audit/audit.rules line={{ item }} insertafter=EOF state=present
  with_items:
    - "-w /etc/group -p wa -k identity"
    - "w /etc/passwd -p wa -k identity"
    - "-w /etc/gshadow -p wa -k identity"
    - "-w /etc/shadow -p wa -k identity"
    - "-w /etc/security/opasswd -p wa -k identity"
  notify: restart auditd
  tags:
    - scored
    - section8.1.5

- name: 8.1.6 Record Events That Modify the System's Network Environment(Scored)
  lineinfile: dest=/etc/audit/audit.rules line={{ item }} insertafter=EOF state=present
  with_items:
    - "-a exit,always -F arch=b64 -S sethostname -S setdomainname -k system-locale"
    - "-a exit,always -F arch=b32 -S sethostname -S setdomainname -k system-locale"
    - "-w /etc/issue -p wa -k system-locale"
    - "-w /etc/issue.net -p wa -k system-locale"
    - "-w /etc/hosts -p wa -k system-locale"
    - "-w /etc/network -p wa -k system-locale"
  when: ansible_machine == "x86_64"
  notify: restart auditd
  tags:
    - scored
    - section8.1.6

- name: 8.1.6 Record Events That Modify the System's Network Environment(Scored)
  lineinfile: dest=/etc/audit/audit.rules line={{ item }} insertafter=EOF state=present
  with_items:
    - "-a exit,always -F arch=b32 -S sethostname -S setdomainname -k system-locale"
    - "-w /etc/issue -p wa -k system-locale"
    - "-w /etc/issue.net -p wa -k system-locale"
    - "-w /etc/hosts -p wa -k system-locale"
    - "-w /etc/network -p wa -k system-locale"
  when: ansible_machine == "i686"
  notify: restart auditd
  tags:
    - scored
    - section8.1.6

- name: 8.1.7 Record Events That Modify the System's Mandatory Access Controls (Scored)
  lineinfile: dest=/etc/audit/audit.rules line="-w /etc/selinux/ -p wa -k MAC-policy" insertafter=EOF state=present
  notify: restart auditd
  tags:
    - scored
    - section8.1.7

- name: 8.1.8 Collect Login and Logout Events (Scored)
  lineinfile: dest=/etc/audit/audit.rules line={{ item }} insertafter=EOF state=present
  with_items:
    - "-w /var/log/faillog -p wa -k logins"
    - "-w /var/log/lastlog -p wa -k logins"
    - "-w /var/log/tallylog -p wa -k logins"
  notify: restart auditd
  tags:
    - scored
    - section8.1.8

- name: 8.1.9 Collect Session Initiation Information (Scored)
  lineinfile: dest=/etc/audit/audit.rules line={{ item }} insertafter=EOF state=present
  with_items:
    - "-w /var/run/utmp -p wa -k session"
    - "-w /var/log/wtmp -p wa -k session"
    - "-w /var/log/btmp -p wa -k session"
  notify: restart auditd
  tags:
    - scored
    - section8.1.9

- name: 8.1.10 Collect Discretionary Access Control Permission Modification Events (Scored)
  lineinfile: dest=/etc/audit/audit.rules line={{ item }} insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b64 -S chmod -S fchmod -S fchmodat -F auid>=500 \\"
    - "-F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b32 -S chmod -S fchmod -S fchmodat -F auid>=500 \\"
    - "-F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b64 -S chown -S fchown -S fchownat -S lchown -F auid>=500 \\"
    - "-F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b32 -S chown -S fchown -S fchownat -S lchown -F auid>=500 \\"
    - "-F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b64 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S \\"
    - "lremovexattr -S fremovexattr -F auid>=500 -F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b32 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S \\"
    - "lremovexattr -S fremovexattr -F auid>=500 -F auid!=4294967295 -k perm_mod"
  when: ansible_machine == "x86_64"
  notify: restart auditd
  tags:
    - scored
    - section8.1.10

- name: 8.1.10 Collect Discretionary Access Control Permission Modification Events (Scored)
  lineinfile: dest=/etc/audit/audit.rules line={{ item }} insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b32 -S chmod -S fchmod -S fchmodat -F auid>=500 \\"
    - "-F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b32 -S chown -S fchown -S fchownat -S lchown -F auid>=500 \\"
    - "-F auid!=4294967295 -k perm_mod"
    - "-a always,exit -F arch=b32 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S \\"
    - "lremovexattr -S fremovexattr -F auid>=500 -F auid!=4294967295 -k perm_mod"
  when: ansible_machine == "i686"
  notify: restart auditd
  tags:
    - scored
    - section8.1.10

- name: 8.1.11 Collect Unsuccessful Unauthorized Access Attempts to Files (Scored)
  lineinfile: dest=/etc/audit/audit.rules line={{ item }} insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate"
    - "-F exit=-EACCES -F auid>=500 -F auid!=4294967295 -k access"
    - "-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate"
    - "-F exit=-EACCES -F auid>=500 -F auid!=4294967295 -k access"
    - "-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate"
    - "-F exit=-EPERM -F auid>=500 -F auid!=4294967295 -k access"
    - "-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate"
    - "-F exit=-EPERM -F auid>=500 -F auid!=4294967295 -k access"
  when: ansible_machine == "x86_64"
  notify: restart auditd
  tags:
    - scored
    - section8.1.11

- name: 8.1.11 Collect Unsuccessful Unauthorized Access Attempts to Files (Scored)
  lineinfile: dest=/etc/audit/audit.rules line={{ item }} insertafter=EOF state=present
  with_items:
    - "-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate \\"
    - "-F exit=-EACCES -F auid>=500 -F auid!=4294967295 -k access"
    - "-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate \\"
    - "-F exit=-EPERM -F auid>=500 -F auid!=4294967295 -k access"
  when: ansible_machine == "i686"
  notify: restart auditd
  tags:
    - scored
    - section8.1.11

- name: 8.1.12 Collect Use of Privileged Commands (Scored)
  shell: /bin/find {/usr/local/sbin,/usr/local/bin,/sbin,/bin,/usr/sbin,/usr/bin} -xdev \( -perm -4000 -o -perm -2000 \) -type f | awk '{print "-a always,exit -F path=" $1 " -F perm=x -F auid>=500 -F auid!=4294967295 -k privileged" }'
  register: privileged_programs
  tags:
    - scored
    - section8.1.12

- name: 8.1.12 Collect Use of Privileged Commands (Scored)
  lineinfile: dest=/etc/audit/audit.rules line={{ item }} insertafter=EOF state=present
  with_items: privileged_programs.stdout_lines
  when: privileged_programs is defined
  tags:
    - scored
    - section8.1.12


# vim: set sw=2 ts=2:
